### ISSUE TITLE
laravel error $queryCollector = $this->collectors['queries'];

### ISSUE THREAD

**Issue by kalsolio** [shieldfy/shieldfy-php-client#29]
public function attachQuery($query)
    {
        // $queryCollector = $this->collectors['queries'];
        // $queryCollector->handler('event', $query->sql, $query->bindings);
    }

**Comment by kalsolio** [comment]
I fix it like this.
in ShieldfyMiddleware
        DB::listen(function ($query,$bindings) use ($guard) {
            $guard->attachQuery($query,$bindings);
        });

in Guard

    public function attachQuery($query,$bindings)
    {
        $queryCollector = $this->collectors['queries'];
        $queryCollector->handler('event', $query, $bindings);
    }

**Comment by netcode** [comment]
@kalsolio 
Thanks for reporting that
It seems that issue is occur in laravel < 5.2 , see [here](https://laravel.com/docs/5.1/database)
```
 DB::listen(function($sql, $bindings, $time) {
            //
 });
```
It changed to object since 5.2, see [here](https://laravel.com/docs/5.2/database)
```
DB::listen(function ($query) {
            // $query->sql
            // $query->bindings
            // $query->time
 });
```


We will update the laravel package to address this issue , thanks again , much appreciated.
@khemso  @7snovic please follow up to fix this at laravel-client asap.
